/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './../routes/__root'
import { Route as IndexRouteImport } from './../routes/index'
import { Route as AccountRouteImport } from './../routes/account'
import { Route as ItinerariesRouteImport } from './../routes/itineraries'
import { Route as SignInRouteImport } from './../routes/sign-in'
import { Route as AscentsAscentIdRouteImport } from './../routes/ascents/$ascentId'
import { Route as AscentsNewRouteImport } from './../routes/ascents/new'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountRoute = AccountRouteImport.update({
  id: '/account',
  path: '/account',
  getParentRoute: () => rootRouteImport,
} as any)
const ItinerariesRoute = ItinerariesRouteImport.update({
  id: '/itineraries',
  path: '/itineraries',
  getParentRoute: () => rootRouteImport,
} as any)
const SignInRoute = SignInRouteImport.update({
  id: '/sign-in',
  path: '/sign-in',
  getParentRoute: () => rootRouteImport,
} as any)
const AscentsAscentIdRoute = AscentsAscentIdRouteImport.update({
  id: '/ascents/$ascentId',
  path: '/ascents/$ascentId',
  getParentRoute: () => rootRouteImport,
} as any)
const AscentsNewRoute = AscentsNewRouteImport.update({
  id: '/ascents/new',
  path: '/ascents/new',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/account': typeof AccountRoute
  '/itineraries': typeof ItinerariesRoute
  '/sign-in': typeof SignInRoute
  '/ascents/$ascentId': typeof AscentsAscentIdRoute
  '/ascents/new': typeof AscentsNewRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/account': typeof AccountRoute
  '/itineraries': typeof ItinerariesRoute
  '/sign-in': typeof SignInRoute
  '/ascents/$ascentId': typeof AscentsAscentIdRoute
  '/ascents/new': typeof AscentsNewRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/account': typeof AccountRoute
  '/itineraries': typeof ItinerariesRoute
  '/sign-in': typeof SignInRoute
  '/ascents/$ascentId': typeof AscentsAscentIdRoute
  '/ascents/new': typeof AscentsNewRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/account'
    | '/itineraries'
    | '/sign-in'
    | '/ascents/$ascentId'
    | '/ascents/new'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/account'
    | '/itineraries'
    | '/sign-in'
    | '/ascents/$ascentId'
    | '/ascents/new'
  id:
    | '__root__'
    | '/'
    | '/account'
    | '/itineraries'
    | '/sign-in'
    | '/ascents/$ascentId'
    | '/ascents/new'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AccountRoute: typeof AccountRoute
  ItinerariesRoute: typeof ItinerariesRoute
  SignInRoute: typeof SignInRoute
  AscentsAscentIdRoute: typeof AscentsAscentIdRoute
  AscentsNewRoute: typeof AscentsNewRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/account': {
      id: '/account'
      path: '/account'
      fullPath: '/account'
      preLoaderRoute: typeof AccountRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/itineraries': {
      id: '/itineraries'
      path: '/itineraries'
      fullPath: '/itineraries'
      preLoaderRoute: typeof ItinerariesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sign-in': {
      id: '/sign-in'
      path: '/sign-in'
      fullPath: '/sign-in'
      preLoaderRoute: typeof SignInRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ascents/$ascentId': {
      id: '/ascents/$ascentId'
      path: '/ascents/$ascentId'
      fullPath: '/ascents/$ascentId'
      preLoaderRoute: typeof AscentsAscentIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ascents/new': {
      id: '/ascents/new'
      path: '/ascents/new'
      fullPath: '/ascents/new'
      preLoaderRoute: typeof AscentsNewRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AccountRoute: AccountRoute,
  ItinerariesRoute: ItinerariesRoute,
  SignInRoute: SignInRoute,
  AscentsAscentIdRoute: AscentsAscentIdRoute,
  AscentsNewRoute: AscentsNewRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
