/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Liveness probe */
        get: operations["getHealth"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * The signed-in Visitor's account
         * @description Created on first use, named after the identity.
         */
        get: operations["getMyAccount"];
        put?: never;
        post?: never;
        /**
         * Delete the signed-in Visitor's account
         * @description Deletes their identity, then everything kept about them; the Ascents they added stay, without any link to them.
         */
        delete: operations["deleteMyAccount"];
        options?: never;
        head?: never;
        /** Change the signed-in Visitor's display name or Flat Pace */
        patch: operations["updateMyAccount"];
        trace?: never;
    };
    "/saved-itineraries": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** The signed-in Visitor's Saved Itineraries, newest first */
        get: operations["listSavedItineraries"];
        put?: never;
        /**
         * Keep a proposal as a Saved Itinerary
         * @description A frozen copy of a Loop, Uphill Itinerary or Hill Session, as proposed.
         */
        post: operations["saveItinerary"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/saved-itineraries/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** A Saved Itinerary with its proposal */
        get: operations["getSavedItinerary"];
        put?: never;
        post?: never;
        /** Delete a Saved Itinerary */
        delete: operations["deleteSavedItinerary"];
        options?: never;
        head?: never;
        /** Rename a Saved Itinerary */
        patch: operations["renameSavedItinerary"];
        trace?: never;
    };
    "/strava/authorize": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Strava's authorisation page for the signed-in Visitor
         * @description Strava sends the Visitor back to the frontend with a code and this state, for `POST /strava/connection`.
         */
        get: operations["authorizeStrava"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/strava/connection": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** The signed-in Visitor's Strava Connection */
        get: operations["getStravaConnection"];
        put?: never;
        /**
         * Make the Strava Connection with the code Strava sent back
         * @description Then imports the runs and trail runs of the last three months, as far as Strava’s limits allow.
         */
        post: operations["connectStrava"];
        /**
         * End the Strava Connection
         * @description Withdraws ClimbSpot’s access at Strava when Strava can be reached, and erases everything kept from Strava.
         */
        delete: operations["endStravaConnection"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/strava/sync": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Import the Recorded Runs started since the latest one
         * @description Runs and trail runs only. Stopping at Strava’s limits keeps what was imported; the next synchronisation carries on.
         */
        post: operations["syncStrava"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/ascents": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Catalogue an Ascent from a GPX file */
        post: operations["createAscent"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/ascents/nearby": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Find the Ascents whose Start is closest to a position
         * @description With a signed-in Visitor's token, each Ascent they went up carries their best Ascent Time.
         */
        get: operations["findAscentsNearby"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/ascents/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get an Ascent with its path and Elevation Profile */
        get: operations["getAscent"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/ascents/{id}/my-times": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * The signed-in Visitor's Ascent Times on an Ascent, newest first
         * @description Found in their Recorded Runs through their Strava Connection; only for them.
         */
        get: operations["getMyAscentTimes"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/itineraries/loops": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Generate Loops from a point
         * @description Up to three Loops starting and ending at `start`, never shorter than `distance` and at most 20 % longer, matching Relief first. Close proposals list their `differences`.
         */
        post: operations["generateLoops"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/itineraries/uphill": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Find Uphill Itineraries near a point
         * @description Up to three proposals going up near `start`, never shorter than `length` and at most 20 % longer, best first. Close proposals list their `differences`.
         */
        post: operations["findUphillItineraries"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/itineraries/sessions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Plan Hill Sessions from a point
         * @description Up to three Hill Sessions near `start`: Repeats of exactly `repeatLength` within the Gradient range, with a Warm-up from `start` to their foot and the same way back, best first (exact, steady, shortest Warm-up). Running Activities only.
         */
        post: operations["planHillSessions"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        ApiError: {
            error: {
                /** @example ROUTE_NOT_FOUND */
                code: string;
                message: string;
                details?: unknown[];
            };
        };
        HealthResponse: {
            /** @enum {string} */
            status: "ok";
        };
        Account: {
            /** @description Private to the Visitor. */
            displayName: string;
            email: string | null;
            /**
             * @description The Flat Pace that applies: the one stated, or else the one from Strava.
             * @example 330
             */
            flatPace: number | null;
            /** @enum {string|null} */
            flatPaceSource: "stated" | "strava" | null;
            /**
             * @description The Flat Pace from Strava, even when a stated one applies.
             * @example 330
             */
            stravaFlatPace: number | null;
        };
        AccountChanges: {
            displayName?: string;
            /**
             * @description A stated Flat Pace, or `null` to go back to the one from Strava.
             * @example 330
             */
            flatPace?: number | null;
        };
        SavedItinerary: {
            /** Format: uuid */
            id: string;
            name: string;
            /** @enum {string} */
            kind: "loop" | "uphill" | "session";
            /** @description Metres; the whole session for a Hill Session. */
            length: number;
            /** Format: date-time */
            savedAt: string;
            proposal: components["schemas"]["LoopItinerary"] | components["schemas"]["UphillItinerary"] | components["schemas"]["HillSession"];
        };
        LoopItinerary: {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            kind: "loop";
            /** @description True when the proposal matches the request. */
            exact: boolean;
            differences: components["schemas"]["ItineraryDifference"][];
            /** @description GeoJSON LineString ([longitude, latitude] pairs). */
            path: {
                /** @enum {string} */
                type: "LineString";
                coordinates: [
                    number,
                    number
                ][];
            };
            elevationProfile: {
                /** @description Distance from the beginning, in metres. */
                distance: number;
                /** @description Elevation, in metres. */
                elevation: number;
            }[];
            /** @description Length along the path, in metres. */
            length: number;
            /** @description Sum of every rise along the path, in metres. */
            heightGained: number;
            effort?: components["schemas"]["Effort"];
            relief: components["schemas"]["Relief"];
        };
        ItineraryDifference: {
            /** @enum {string} */
            kind: "gradient";
            min: number;
            max: number;
            /** @description Average Gradient of the proposal, as a ratio (0.08 = 8 %). */
            actual: number;
        } | {
            /** @enum {string} */
            kind: "relief";
            /** @enum {string} */
            wanted: "flat" | "rolling" | "hilly";
            /** @enum {string} */
            actual: "flat" | "rolling" | "hilly";
        };
        /** @description How hard the path is to run; only given for running. */
        Effort: {
            /**
             * @description Length in km plus one per 100 m of Height Gained, rounded to 0.1.
             * @example 4.8
             */
            kmEffort: number;
            /** @description Distance on the flat costing a runner as much as the path (Minetti, descents at best 10 % faster), in metres. */
            flatEquivalentDistance: number;
        };
        /** @enum {string} */
        Relief: "flat" | "rolling" | "hilly";
        UphillItinerary: {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            kind: "uphill";
            /** @description True when the proposal matches the request. */
            exact: boolean;
            differences: components["schemas"]["ItineraryDifference"][];
            /** @description GeoJSON LineString ([longitude, latitude] pairs). */
            path: {
                /** @enum {string} */
                type: "LineString";
                coordinates: [
                    number,
                    number
                ][];
            };
            elevationProfile: {
                /** @description Distance from the beginning, in metres. */
                distance: number;
                /** @description Elevation, in metres. */
                elevation: number;
            }[];
            /** @description Length along the path, in metres. */
            length: number;
            /** @description Sum of every rise along the path, in metres. */
            heightGained: number;
            effort?: components["schemas"]["Effort"];
            start: components["schemas"]["ItineraryPoint"];
            top: components["schemas"]["ItineraryPoint"];
            /** @description Top elevation minus start elevation, in metres. */
            elevationGain: number;
            /** @description Average Gradient, as a ratio (0.08 = 8 %). */
            averageGradient: number;
            /** @description Steepest Gradient over at least 100 m, as a ratio (0.08 = 8 %). */
            maximumGradient: number;
            difficultyScore: number;
            category: components["schemas"]["Category"];
            /** @description Distance from the Visitor's point to the start, in metres. */
            distanceToStart: number;
        };
        ItineraryPoint: {
            latitude: number;
            longitude: number;
            /** @description Elevation, in metres. */
            elevation: number;
        };
        /** @enum {string} */
        Category: "uncategorized" | "cat4" | "cat3" | "cat2" | "cat1" | "hc";
        HillSession: {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            kind: "session";
            /** @description True when the proposal matches the request. */
            exact: boolean;
            differences: components["schemas"]["ItineraryDifference"][];
            repeats: number;
            /** @description The Uphill Itinerary run up for each Repeat. */
            repeat: {
                /** @description GeoJSON LineString ([longitude, latitude] pairs). */
                path: {
                    /** @enum {string} */
                    type: "LineString";
                    coordinates: [
                        number,
                        number
                    ][];
                };
                elevationProfile: {
                    /** @description Distance from the beginning, in metres. */
                    distance: number;
                    /** @description Elevation, in metres. */
                    elevation: number;
                }[];
                /** @description Length of one Repeat, in metres. */
                length: number;
                /** @description Average Gradient of the Repeat, as a ratio (0.08 = 8 %). */
                averageGradient: number;
                /** @description Steepest Gradient of the Repeat, as a ratio (0.08 = 8 %). */
                maximumGradient: number;
                start: components["schemas"]["ItineraryPoint"];
                top: components["schemas"]["ItineraryPoint"];
            };
            /** @description From `start` to the foot of the Repeat; the Cool-down is the same way back. */
            warmUp: {
                /** @description GeoJSON LineString ([longitude, latitude] pairs). */
                path: {
                    /** @enum {string} */
                    type: "LineString";
                    coordinates: [
                        number,
                        number
                    ][];
                };
                elevationProfile: {
                    /** @description Distance from the beginning, in metres. */
                    distance: number;
                    /** @description Elevation, in metres. */
                    elevation: number;
                }[];
                /** @description Length of the Warm-up, in metres. */
                length: number;
            };
            /** @description Warm-up, Repeats and Recoveries, and Cool-down together. */
            totals: {
                /** @description Length of the whole session, in metres. */
                length: number;
                /** @description Every rise over the whole session, in metres. */
                heightGained: number;
                effort: components["schemas"]["Effort"];
            };
        };
        NewSavedItinerary: {
            name: string;
            proposal: components["schemas"]["LoopItinerary"] | components["schemas"]["UphillItinerary"] | components["schemas"]["HillSession"];
        };
        SavedItineraries: {
            savedItineraries: components["schemas"]["SavedItinerarySummary"][];
        };
        SavedItinerarySummary: {
            /** Format: uuid */
            id: string;
            name: string;
            /** @enum {string} */
            kind: "loop" | "uphill" | "session";
            /** @description Metres; the whole session for a Hill Session. */
            length: number;
            /** Format: date-time */
            savedAt: string;
        };
        SavedItineraryChanges: {
            name: string;
        };
        StravaAuthorization: {
            /**
             * Format: uri
             * @description Strava's page where the Visitor agrees.
             */
            url: string;
        };
        StravaConnection: {
            /**
             * @description `lost`: the Visitor withdrew ClimbSpot at Strava, and needs to connect again.
             * @enum {string}
             */
            status: "none" | "connected" | "lost";
            athlete: {
                name: string;
            } | null;
            /** Format: date-time */
            connectedAt: string | null;
            /**
             * Format: date-time
             * @description When Recorded Runs were last imported in full.
             */
            lastSyncAt: string | null;
            recordedRuns: number;
        };
        StravaConnectionRequest: {
            /** @description The code Strava sent back. */
            code: string;
            /** @description The state Strava sent back with it. */
            state: string;
        };
        Ascent: {
            /** Format: uuid */
            id: string;
            name: string;
            surface: components["schemas"]["Surface"];
            activities: components["schemas"]["Activity"][];
            start: components["schemas"]["AscentPoint"];
            top: components["schemas"]["AscentPoint"];
            /** @description Length along the path, in metres. */
            length: number;
            /** @description Top elevation minus Start elevation, in metres. */
            elevationGain: number;
            /** @description Every rise along the path, Dips included, in metres. */
            heightGained: number;
            /**
             * @description Average Gradient, as a ratio (0.08 = 8 %).
             * @example 0.072
             */
            averageGradient: number;
            /**
             * @description Steepest Gradient over at least 500 m, as a ratio (0.08 = 8 %).
             * @example 0.072
             */
            maximumGradient: number;
            /** @description Length in metres × average Gradient in percent. */
            difficultyScore: number;
            category: components["schemas"]["Category"];
            effort?: components["schemas"]["Effort"];
            /** Format: date-time */
            createdAt: string;
            /** @description GeoJSON LineString from Start to Top ([longitude, latitude] pairs). */
            path: {
                /** @enum {string} */
                type: "LineString";
                coordinates: [
                    number,
                    number
                ][];
            };
            elevationProfile: {
                /** @description Distance from the Start along the path, in metres. */
                distance: number;
                /** @description Elevation, in metres. */
                elevation: number;
            }[];
        };
        /** @enum {string} */
        Surface: "paved" | "gravel" | "trail";
        /** @enum {string} */
        Activity: "running" | "trail_running" | "road_cycling" | "gravel_cycling" | "mountain_biking";
        AscentPoint: {
            latitude: number;
            longitude: number;
            /** @description Elevation, in metres. */
            elevation: number;
        };
        NearbyAscents: {
            ascents: {
                /** Format: uuid */
                id: string;
                name: string;
                surface: components["schemas"]["Surface"];
                activities: components["schemas"]["Activity"][];
                start: components["schemas"]["AscentPoint"];
                top: components["schemas"]["AscentPoint"];
                /** @description Length along the path, in metres. */
                length: number;
                /** @description Top elevation minus Start elevation, in metres. */
                elevationGain: number;
                /** @description Every rise along the path, Dips included, in metres. */
                heightGained: number;
                /**
                 * @description Average Gradient, as a ratio (0.08 = 8 %).
                 * @example 0.072
                 */
                averageGradient: number;
                /**
                 * @description Steepest Gradient over at least 500 m, as a ratio (0.08 = 8 %).
                 * @example 0.072
                 */
                maximumGradient: number;
                /** @description Length in metres × average Gradient in percent. */
                difficultyScore: number;
                category: components["schemas"]["Category"];
                effort?: components["schemas"]["Effort"];
                /** Format: date-time */
                createdAt: string;
                /** @description Geodesic distance from the searched position to the Start, in metres. */
                distanceToStart: number;
                /** @description The signed-in Visitor's best Ascent Time here and how many they have; only for them, and only when they have one. */
                myAscentTimes?: {
                    /** @description Seconds. */
                    best: number;
                    count: number;
                };
            }[];
        };
        MyAscentTimes: {
            ascentTimes: {
                /**
                 * Format: date-time
                 * @description When the Visitor left the Start.
                 */
                startedAt: string;
                seconds: number;
            }[];
        };
        LoopItineraries: {
            itineraries: components["schemas"]["LoopItinerary"][];
        };
        LoopRequest: {
            start: {
                latitude: number;
                longitude: number;
            };
            /** @description Metres; Loops are never shorter and at most 20 % longer. */
            distance: number;
            relief: components["schemas"]["Relief"];
            activity: components["schemas"]["Activity"];
        };
        UphillItineraries: {
            itineraries: components["schemas"]["UphillItinerary"][];
        };
        UphillRequest: {
            start: {
                latitude: number;
                longitude: number;
            };
            /**
             * @description The Itinerary starts within this distance of `start`, in metres.
             * @default 10000
             */
            radius: number;
            /** @description Metres; proposals are never shorter and at most 20 % longer. */
            length: number;
            /** @description Lowest average Gradient wanted, as a ratio (0.08 = 8 %). */
            minGradient: number;
            /** @description Highest average Gradient wanted, as a ratio (0.08 = 8 %). */
            maxGradient: number;
            activity: components["schemas"]["Activity"];
        };
        HillSessions: {
            sessions: components["schemas"]["HillSession"][];
        };
        HillSessionRequest: {
            start: {
                latitude: number;
                longitude: number;
            };
            /**
             * @description The Repeats start within this distance of `start`, in metres.
             * @default 10000
             */
            radius: number;
            /** @description Number of Repeats. */
            repeats: number;
            /** @description Metres; every Repeat is exactly this long. */
            repeatLength: number;
            /** @description Lowest average Gradient of the Repeat, as a ratio (0.08 = 8 %). */
            minGradient: number;
            /** @description Highest average Gradient of the Repeat, as a ratio (0.08 = 8 %). */
            maxGradient: number;
            /**
             * @description A running Activity.
             * @enum {string}
             */
            activity: "running" | "trail_running";
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    getHealth: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The API is up. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthResponse"];
                };
            };
        };
    };
    getMyAccount: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The account. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Account"];
                };
            };
            /** @description `AUTHENTICATION_REQUIRED`: nobody is signed in. */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
        };
    };
    deleteMyAccount: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Deleted. */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description `AUTHENTICATION_REQUIRED`: nobody is signed in. */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
            /** @description `ACCOUNT_DELETION_UNAVAILABLE`: the identity could not be deleted; nothing was erased. */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
        };
    };
    updateMyAccount: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AccountChanges"];
            };
        };
        responses: {
            /** @description The account. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Account"];
                };
            };
            /** @description `VALIDATION_FAILED`: the changes are invalid. */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
            /** @description `AUTHENTICATION_REQUIRED`: nobody is signed in. */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
        };
    };
    listSavedItineraries: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Their summaries. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SavedItineraries"];
                };
            };
            /** @description `AUTHENTICATION_REQUIRED`: nobody is signed in. */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
        };
    };
    saveItinerary: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["NewSavedItinerary"];
            };
        };
        responses: {
            /** @description The Saved Itinerary. */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SavedItinerary"];
                };
            };
            /** @description `VALIDATION_FAILED`: the name or the proposal is invalid. */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
            /** @description `AUTHENTICATION_REQUIRED`: nobody is signed in. */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
            /** @description `SAVED_ITINERARY_TOO_LARGE`: the proposal is too large to keep. */
            413: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
        };
    };
    getSavedItinerary: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The Saved Itinerary. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SavedItinerary"];
                };
            };
            /** @description `AUTHENTICATION_REQUIRED`: nobody is signed in. */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
            /** @description `SAVED_ITINERARY_NOT_FOUND`: the signed-in Visitor has no such Saved Itinerary. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
        };
    };
    deleteSavedItinerary: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Deleted. */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description `AUTHENTICATION_REQUIRED`: nobody is signed in. */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
            /** @description `SAVED_ITINERARY_NOT_FOUND`: the signed-in Visitor has no such Saved Itinerary. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
        };
    };
    renameSavedItinerary: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SavedItineraryChanges"];
            };
        };
        responses: {
            /** @description The Saved Itinerary. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SavedItinerary"];
                };
            };
            /** @description `VALIDATION_FAILED`: the name is invalid. */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
            /** @description `AUTHENTICATION_REQUIRED`: nobody is signed in. */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
            /** @description `SAVED_ITINERARY_NOT_FOUND`: the signed-in Visitor has no such Saved Itinerary. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
        };
    };
    authorizeStrava: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Where to send the Visitor. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StravaAuthorization"];
                };
            };
            /** @description `AUTHENTICATION_REQUIRED`: nobody is signed in. */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
        };
    };
    getStravaConnection: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The Strava Connection. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StravaConnection"];
                };
            };
            /** @description `AUTHENTICATION_REQUIRED`: nobody is signed in. */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
        };
    };
    connectStrava: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["StravaConnectionRequest"];
            };
        };
        responses: {
            /** @description The Strava Connection. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StravaConnection"];
                };
            };
            /** @description `VALIDATION_FAILED`: the code or state is missing. */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
            /** @description `AUTHENTICATION_REQUIRED`: nobody is signed in. */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
            /** @description `STRAVA_AUTHORIZATION_REFUSED`: Strava refused the code, or the state is not the Visitor’s. */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
            /** @description `STRAVA_UNAVAILABLE`: Strava is down or its limits are reached. */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
        };
    };
    endStravaConnection: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Ended. */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description `AUTHENTICATION_REQUIRED`: nobody is signed in. */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
        };
    };
    syncStrava: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The Strava Connection. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StravaConnection"];
                };
            };
            /** @description `AUTHENTICATION_REQUIRED`: nobody is signed in. */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
            /** @description `STRAVA_CONNECTION_LOST`: the Visitor withdrew ClimbSpot at Strava; they need to connect again. */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
            /** @description `STRAVA_UNAVAILABLE`: Strava is down or its limits are reached; what was imported stays. */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
        };
    };
    createAscent: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "multipart/form-data": {
                    name: string;
                    surface: components["schemas"]["Surface"];
                    /**
                     * Format: binary
                     * @description GPX file of the path (track or route).
                     */
                    gpx: string;
                };
            };
        };
        responses: {
            /** @description The Ascent was created. */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Ascent"];
                };
            };
            /** @description `VALIDATION_FAILED`: a field is missing or invalid. */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
            /** @description `AUTHENTICATION_REQUIRED`: only signed-in Visitors add Ascents. */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
            /** @description `GPX_TOO_LARGE`: the file exceeds 5 MB or its path has more than 20,000 points. */
            413: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
            /** @description The upload cannot become an Ascent: `GPX_INVALID` (not a valid GPX file), `GPX_EMPTY` (no track or route with two distinct points), `ASCENT_TOO_LONG` (over 50 km), `ASCENT_TOO_LOW` (gains under 10 m), `ASCENT_TOO_FLAT` (averages under 3 %) or `ASCENT_DIP_TOO_LARGE` (loses more than the larger of 10 m and 10 % of its Elevation Gain in Dips). */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
            /** @description `ELEVATION_UNAVAILABLE`: the terrain model cannot be reached; retry later. */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
        };
    };
    findAscentsNearby: {
        parameters: {
            query: {
                latitude: number;
                longitude: number;
                /** @description Maximum distance to the Start, in metres. */
                radius?: number;
                limit?: number;
                /** @description Only Ascents suitable for one of these Activities. Repeatable. */
                activity?: components["schemas"]["Activity"][];
                /** @description Only Ascents in one of these Categories. Repeatable. */
                category?: components["schemas"]["Category"][];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Ascents within the radius, nearest Start first. Empty when none. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["NearbyAscents"];
                };
            };
            /** @description `VALIDATION_FAILED`: a query parameter is missing or out of range. */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
        };
    };
    getAscent: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The Ascent. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Ascent"];
                };
            };
            /** @description `VALIDATION_FAILED`: the id is not a UUID. */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
            /** @description `ASCENT_NOT_FOUND`: no Ascent has this id. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
        };
    };
    getMyAscentTimes: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Their Ascent Times; empty when they have none. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MyAscentTimes"];
                };
            };
            /** @description `VALIDATION_FAILED`: the id is not a UUID. */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
            /** @description `AUTHENTICATION_REQUIRED`: nobody is signed in. */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
            /** @description `ASCENT_NOT_FOUND`: no Ascent has this id. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
        };
    };
    generateLoops: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LoopRequest"];
            };
        };
        responses: {
            /** @description Proposals, possibly none. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LoopItineraries"];
                };
            };
            /** @description `VALIDATION_FAILED`: the request is invalid. */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
            /** @description `ROUTING_UNAVAILABLE`: routing is temporarily unavailable; retry later. */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
        };
    };
    findUphillItineraries: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UphillRequest"];
            };
        };
        responses: {
            /** @description Proposals, possibly none. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UphillItineraries"];
                };
            };
            /** @description `VALIDATION_FAILED`: the request is invalid. */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
            /** @description `ROUTING_UNAVAILABLE`: routing is temporarily unavailable; retry later. */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
        };
    };
    planHillSessions: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["HillSessionRequest"];
            };
        };
        responses: {
            /** @description Sessions, possibly none. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HillSessions"];
                };
            };
            /** @description `VALIDATION_FAILED`: the request is invalid. */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
            /** @description `ROUTING_UNAVAILABLE`: routing is temporarily unavailable; retry later. */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
        };
    };
}
